/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MusteriHizmetleriRouteImport } from './routes/musteri-hizmetleri'
import { Route as KurumsalRouteImport } from './routes/kurumsal'
import { Route as BizeUlasinRouteImport } from './routes/bize-ulasin'
import { Route as BilgiBankasiRouteImport } from './routes/bilgi-bankasi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KurumsalLogolarimizRouteImport } from './routes/kurumsal.logolarimiz'
import { Route as KurumsalLeedSertifikasiRouteImport } from './routes/kurumsal.leed-sertifikasi'
import { Route as KurumsalKvkkRouteImport } from './routes/kurumsal.kvkk'
import { Route as KurumsalInsanKaynaklariRouteImport } from './routes/kurumsal.insan-kaynaklari'
import { Route as KurumsalHakkimizdaRouteImport } from './routes/kurumsal.hakkimizda'
import { Route as KurumsalBilgiToplumuRouteImport } from './routes/kurumsal.bilgi-toplumu'
import { Route as KurumsalBasinOdasiRouteImport } from './routes/kurumsal.basin-odasi'

const MusteriHizmetleriRoute = MusteriHizmetleriRouteImport.update({
  id: '/musteri-hizmetleri',
  path: '/musteri-hizmetleri',
  getParentRoute: () => rootRouteImport,
} as any)
const KurumsalRoute = KurumsalRouteImport.update({
  id: '/kurumsal',
  path: '/kurumsal',
  getParentRoute: () => rootRouteImport,
} as any)
const BizeUlasinRoute = BizeUlasinRouteImport.update({
  id: '/bize-ulasin',
  path: '/bize-ulasin',
  getParentRoute: () => rootRouteImport,
} as any)
const BilgiBankasiRoute = BilgiBankasiRouteImport.update({
  id: '/bilgi-bankasi',
  path: '/bilgi-bankasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurumsalLogolarimizRoute = KurumsalLogolarimizRouteImport.update({
  id: '/logolarimiz',
  path: '/logolarimiz',
  getParentRoute: () => KurumsalRoute,
} as any)
const KurumsalLeedSertifikasiRoute = KurumsalLeedSertifikasiRouteImport.update({
  id: '/leed-sertifikasi',
  path: '/leed-sertifikasi',
  getParentRoute: () => KurumsalRoute,
} as any)
const KurumsalKvkkRoute = KurumsalKvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => KurumsalRoute,
} as any)
const KurumsalInsanKaynaklariRoute = KurumsalInsanKaynaklariRouteImport.update({
  id: '/insan-kaynaklari',
  path: '/insan-kaynaklari',
  getParentRoute: () => KurumsalRoute,
} as any)
const KurumsalHakkimizdaRoute = KurumsalHakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => KurumsalRoute,
} as any)
const KurumsalBilgiToplumuRoute = KurumsalBilgiToplumuRouteImport.update({
  id: '/bilgi-toplumu',
  path: '/bilgi-toplumu',
  getParentRoute: () => KurumsalRoute,
} as any)
const KurumsalBasinOdasiRoute = KurumsalBasinOdasiRouteImport.update({
  id: '/basin-odasi',
  path: '/basin-odasi',
  getParentRoute: () => KurumsalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilgi-bankasi': typeof BilgiBankasiRoute
  '/bize-ulasin': typeof BizeUlasinRoute
  '/kurumsal': typeof KurumsalRouteWithChildren
  '/musteri-hizmetleri': typeof MusteriHizmetleriRoute
  '/kurumsal/basin-odasi': typeof KurumsalBasinOdasiRoute
  '/kurumsal/bilgi-toplumu': typeof KurumsalBilgiToplumuRoute
  '/kurumsal/hakkimizda': typeof KurumsalHakkimizdaRoute
  '/kurumsal/insan-kaynaklari': typeof KurumsalInsanKaynaklariRoute
  '/kurumsal/kvkk': typeof KurumsalKvkkRoute
  '/kurumsal/leed-sertifikasi': typeof KurumsalLeedSertifikasiRoute
  '/kurumsal/logolarimiz': typeof KurumsalLogolarimizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilgi-bankasi': typeof BilgiBankasiRoute
  '/bize-ulasin': typeof BizeUlasinRoute
  '/kurumsal': typeof KurumsalRouteWithChildren
  '/musteri-hizmetleri': typeof MusteriHizmetleriRoute
  '/kurumsal/basin-odasi': typeof KurumsalBasinOdasiRoute
  '/kurumsal/bilgi-toplumu': typeof KurumsalBilgiToplumuRoute
  '/kurumsal/hakkimizda': typeof KurumsalHakkimizdaRoute
  '/kurumsal/insan-kaynaklari': typeof KurumsalInsanKaynaklariRoute
  '/kurumsal/kvkk': typeof KurumsalKvkkRoute
  '/kurumsal/leed-sertifikasi': typeof KurumsalLeedSertifikasiRoute
  '/kurumsal/logolarimiz': typeof KurumsalLogolarimizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilgi-bankasi': typeof BilgiBankasiRoute
  '/bize-ulasin': typeof BizeUlasinRoute
  '/kurumsal': typeof KurumsalRouteWithChildren
  '/musteri-hizmetleri': typeof MusteriHizmetleriRoute
  '/kurumsal/basin-odasi': typeof KurumsalBasinOdasiRoute
  '/kurumsal/bilgi-toplumu': typeof KurumsalBilgiToplumuRoute
  '/kurumsal/hakkimizda': typeof KurumsalHakkimizdaRoute
  '/kurumsal/insan-kaynaklari': typeof KurumsalInsanKaynaklariRoute
  '/kurumsal/kvkk': typeof KurumsalKvkkRoute
  '/kurumsal/leed-sertifikasi': typeof KurumsalLeedSertifikasiRoute
  '/kurumsal/logolarimiz': typeof KurumsalLogolarimizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilgi-bankasi'
    | '/bize-ulasin'
    | '/kurumsal'
    | '/musteri-hizmetleri'
    | '/kurumsal/basin-odasi'
    | '/kurumsal/bilgi-toplumu'
    | '/kurumsal/hakkimizda'
    | '/kurumsal/insan-kaynaklari'
    | '/kurumsal/kvkk'
    | '/kurumsal/leed-sertifikasi'
    | '/kurumsal/logolarimiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bilgi-bankasi'
    | '/bize-ulasin'
    | '/kurumsal'
    | '/musteri-hizmetleri'
    | '/kurumsal/basin-odasi'
    | '/kurumsal/bilgi-toplumu'
    | '/kurumsal/hakkimizda'
    | '/kurumsal/insan-kaynaklari'
    | '/kurumsal/kvkk'
    | '/kurumsal/leed-sertifikasi'
    | '/kurumsal/logolarimiz'
  id:
    | '__root__'
    | '/'
    | '/bilgi-bankasi'
    | '/bize-ulasin'
    | '/kurumsal'
    | '/musteri-hizmetleri'
    | '/kurumsal/basin-odasi'
    | '/kurumsal/bilgi-toplumu'
    | '/kurumsal/hakkimizda'
    | '/kurumsal/insan-kaynaklari'
    | '/kurumsal/kvkk'
    | '/kurumsal/leed-sertifikasi'
    | '/kurumsal/logolarimiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilgiBankasiRoute: typeof BilgiBankasiRoute
  BizeUlasinRoute: typeof BizeUlasinRoute
  KurumsalRoute: typeof KurumsalRouteWithChildren
  MusteriHizmetleriRoute: typeof MusteriHizmetleriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/musteri-hizmetleri': {
      id: '/musteri-hizmetleri'
      path: '/musteri-hizmetleri'
      fullPath: '/musteri-hizmetleri'
      preLoaderRoute: typeof MusteriHizmetleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurumsal': {
      id: '/kurumsal'
      path: '/kurumsal'
      fullPath: '/kurumsal'
      preLoaderRoute: typeof KurumsalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bize-ulasin': {
      id: '/bize-ulasin'
      path: '/bize-ulasin'
      fullPath: '/bize-ulasin'
      preLoaderRoute: typeof BizeUlasinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilgi-bankasi': {
      id: '/bilgi-bankasi'
      path: '/bilgi-bankasi'
      fullPath: '/bilgi-bankasi'
      preLoaderRoute: typeof BilgiBankasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurumsal/logolarimiz': {
      id: '/kurumsal/logolarimiz'
      path: '/logolarimiz'
      fullPath: '/kurumsal/logolarimiz'
      preLoaderRoute: typeof KurumsalLogolarimizRouteImport
      parentRoute: typeof KurumsalRoute
    }
    '/kurumsal/leed-sertifikasi': {
      id: '/kurumsal/leed-sertifikasi'
      path: '/leed-sertifikasi'
      fullPath: '/kurumsal/leed-sertifikasi'
      preLoaderRoute: typeof KurumsalLeedSertifikasiRouteImport
      parentRoute: typeof KurumsalRoute
    }
    '/kurumsal/kvkk': {
      id: '/kurumsal/kvkk'
      path: '/kvkk'
      fullPath: '/kurumsal/kvkk'
      preLoaderRoute: typeof KurumsalKvkkRouteImport
      parentRoute: typeof KurumsalRoute
    }
    '/kurumsal/insan-kaynaklari': {
      id: '/kurumsal/insan-kaynaklari'
      path: '/insan-kaynaklari'
      fullPath: '/kurumsal/insan-kaynaklari'
      preLoaderRoute: typeof KurumsalInsanKaynaklariRouteImport
      parentRoute: typeof KurumsalRoute
    }
    '/kurumsal/hakkimizda': {
      id: '/kurumsal/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/kurumsal/hakkimizda'
      preLoaderRoute: typeof KurumsalHakkimizdaRouteImport
      parentRoute: typeof KurumsalRoute
    }
    '/kurumsal/bilgi-toplumu': {
      id: '/kurumsal/bilgi-toplumu'
      path: '/bilgi-toplumu'
      fullPath: '/kurumsal/bilgi-toplumu'
      preLoaderRoute: typeof KurumsalBilgiToplumuRouteImport
      parentRoute: typeof KurumsalRoute
    }
    '/kurumsal/basin-odasi': {
      id: '/kurumsal/basin-odasi'
      path: '/basin-odasi'
      fullPath: '/kurumsal/basin-odasi'
      preLoaderRoute: typeof KurumsalBasinOdasiRouteImport
      parentRoute: typeof KurumsalRoute
    }
  }
}

interface KurumsalRouteChildren {
  KurumsalBasinOdasiRoute: typeof KurumsalBasinOdasiRoute
  KurumsalBilgiToplumuRoute: typeof KurumsalBilgiToplumuRoute
  KurumsalHakkimizdaRoute: typeof KurumsalHakkimizdaRoute
  KurumsalInsanKaynaklariRoute: typeof KurumsalInsanKaynaklariRoute
  KurumsalKvkkRoute: typeof KurumsalKvkkRoute
  KurumsalLeedSertifikasiRoute: typeof KurumsalLeedSertifikasiRoute
  KurumsalLogolarimizRoute: typeof KurumsalLogolarimizRoute
}

const KurumsalRouteChildren: KurumsalRouteChildren = {
  KurumsalBasinOdasiRoute: KurumsalBasinOdasiRoute,
  KurumsalBilgiToplumuRoute: KurumsalBilgiToplumuRoute,
  KurumsalHakkimizdaRoute: KurumsalHakkimizdaRoute,
  KurumsalInsanKaynaklariRoute: KurumsalInsanKaynaklariRoute,
  KurumsalKvkkRoute: KurumsalKvkkRoute,
  KurumsalLeedSertifikasiRoute: KurumsalLeedSertifikasiRoute,
  KurumsalLogolarimizRoute: KurumsalLogolarimizRoute,
}

const KurumsalRouteWithChildren = KurumsalRoute._addFileChildren(
  KurumsalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilgiBankasiRoute: BilgiBankasiRoute,
  BizeUlasinRoute: BizeUlasinRoute,
  KurumsalRoute: KurumsalRouteWithChildren,
  MusteriHizmetleriRoute: MusteriHizmetleriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
